### ISSUE TITLE
Error on Enabling the Plugin

### ISSUE THREAD

**Issue by ismailsunni** [OpenGeoLabs/czech_slovak_freegeodata#37]
When I tried to install the plugin, I got this error message:

```
Couldn't load plugin 'czech_slovak_freegeodata' due to an error when calling its classFactory() method 

IndexError: list index out of range 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/isunni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/czech_slovak_freegeodata/__init__.py", line 35, in classFactory
    from .Geo_Data import GeoData
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/isunni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/czech_slovak_freegeodata/Geo_Data.py", line 36, in 
    from .Geo_Data_dialog import GeoDataDialog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/isunni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/czech_slovak_freegeodata/Geo_Data_dialog.py", line 46, in 
    from .crs_trans.ShiftGrid import ShiftGrid
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/isunni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/czech_slovak_freegeodata/crs_trans/ShiftGrid.py", line 13, in 
    class ShiftGrid:
  File "/home/isunni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/czech_slovak_freegeodata/crs_trans/ShiftGrid.py", line 19, in ShiftGrid
    gridDirectory = QgsProjUtils.searchPaths()[-1]
IndexError: list index out of range


Python version: 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0] 
QGIS version: 3.16.3-Hannover Hannover, 94ac9f21b8 

```

I tried to disable then enable it again, and I still get the error.

I use Ubuntu 18.04, QGIS 3.16.3

Thanks!

**Comment by PetoP** [comment]
Hi,

thank you very much for reporting this issue.

It seems that plugin is unable to identify directory into which shift grid files have to be downloaded. Could you please run following command in QGIS Python console and send me the output?

QgsProjUtils.searchPaths()

According to python trace you have provided I would expect empty list, however if there will be something, it will point into your home directory, so maybe you will wish to "censor" it little bit before you post it here.

Best regards,
Peter

**Comment by ismailsunni** [comment]
Hi @PetoP 
It's an empty list:
```
Python Console
Use iface to access QGIS API interface or Type help(iface) for more info
Security warning: typing commands from an untrusted source can harm your computer
QgsProjUtils.searchPaths()
[]
```

**Comment by PetoP** [comment]
Hi,

it seems that your version of Proj is older than version 6.

You can get version of Proj that QGIS is using by running following command inside QGIS Python console: 

QgsProjUtils.projVersionMajor()

If it is true that your version of Proj is older than 6, part of plugin dealing with CRS transformations is incompatible and will never work with older Proj versions. Only think I can do for you then is that I will disable this part of plugin for older versions of Proj. Then you will be able to load all data sources, but coordinate transformations will not work for you.

Best regards,
Peter

**Comment by ismailsunni** [comment]
Ah yes, my Proj version is 4.

I think it's better for me to update my Proj, hopefully in 2-3 weeks. No need to worry though, I only want to try the plugin to get some idea of how a geodata plugin works.

Thanks for your great response :)
